import "@styles/pages/_Platform.scss";
import Header from "@components/Header/Header";
import Aside from "@components/Aside/Aside";
import PlatformSession from "@components/PlatformSession/PlatformSession";

export const metadata = {
  title: "УЧЕБНАЯ ПЛАТФОРМА 1.0",
  description: "Generated by create next app",
  authors: [{name: 'Just-site.ru'}]
};

export default function PlatformLayout({ children }) {
  return (
      <>
        <Header />
        <PlatformSession>
          <Aside />
          {children}
        </PlatformSession>
      </>
  );
}