import { Manrope } from "next/font/google";
import "@styles/globals.scss";
import { AuthProvider } from "./Providers";

const manrope = Manrope({ 
  subsets: ["cyrillic", "latin"],
  preload: true,
  variable: "--manrope"
});

export const metadata = {
  title: "УЧЕБНАЯ ПЛАТФОРМА 1.0 | Авторизация",
  description: "Generated by create next app",
  authors: [{name: 'Just-site.ru'}]
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={manrope.variable}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
