export const metadata = {
  title: "УЧЕБНАЯ ПЛАТФОРМА 1.0 | Регистрация",
  description: "Generated by create next app",
  authors: [{name: 'Just-site.ru'}]
};

export default function RegisterLayout({ children }) {
  return children;
}